### ISSUE TITLE
fpsdisplaysink cannot display the video

### ISSUE THREAD

**Issue by fthiery** [wmanley/pulsevideo#3] opened 2015-02-11 16:21 UTC
pulsevideo --source-pipeline="videotestsrc is-live=true" --caps="video/x-raw, format=I420, width=320, height=240, framerate=25/1"

    gst-launch-1.0 dbusvideosourcesrc ! queue ! fpsdisplaysink -v
    /GstPipeline:pipeline0/GstFPSDisplaySink:fpsdisplaysink0/GstAutoVideoSink:fps-display-video_sink.GstGhostPad:sink.GstProxyPad:proxypad2: caps = "video/x-raw\,\ format\=\(string\)I420\,\ width\=\(int\)320\,\ height\=\(int\)240\,\ framerate\=\(fraction\)25/1"

Displays a black picture with a lot of prints:

    ret is -1 22

Where the following works as expected:

    gst-launch-1.0 videotestsrc ! "video/x-raw, format=(string)I420, width=(int)320, height=(int)240,framerate=(fraction)25/1" ! fpsdisplaysink

**Comment by wmanley** [comment] 2015-07-27 14:05
Since adding the debugging to the filenames in b59a36aad2580b251a75b2a5d962e9dbe3dcd7af I can confirm the cause of this issue:  [`gst_tmpfile_allocator_alloc`](https://github.com/wmanley/pulsevideo/blob/master/gst/tmpfile/gsttmpfileallocator.c#L115) is only being called once and then the `GstMemory` is being reused again and again.  This is wrong because the backing memory is still in use, it's just being used by the downstream process.

The fix will involve understanding the interaction between our `GstTmpFileAllocator`, `GstBaseTransform` and the `GstBufferPool`s that are used implicitly.

**Comment by wmanley** [comment] 2015-07-27 14:06
Note this is likely to be caused by the same issue as #1.

**Comment by wmanley** [comment] 2015-08-07 12:44
Fixed by PR #8

**Closed by wmanley** 2015-08-07 12:44 UTC
